version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/projects/nyar-error"
    target-branch: "dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/projects/nyar-hir"
    target-branch: "dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/projects/nyar-wasm"
    target-branch: "dev"
    schedule:
      interval: "daily"